exports.seed = async function (knex) {
    await knex("countries").del();
    await knex('countries').insert([
        { country_name: 'Afghanistan', country_code: 'AF', ambulance_phone: '102' },
        { country_name: 'Albania', country_code: 'AL', ambulance_phone: '127' },
        { country_name: 'Algeria', country_code: 'DZ', ambulance_phone: '14' },
        { country_name: 'Andorra', country_code: 'AD', ambulance_phone: '112' },
        { country_name: 'Angola', country_code: 'AO', ambulance_phone: '118' },
        { country_name: 'Antigua and Barbuda', country_code: 'AG', ambulance_phone: '911' },
        { country_name: 'Argentina', country_code: 'AR', ambulance_phone: '107' },
        { country_name: 'Armenia', country_code: 'AM', ambulance_phone: '103' },
        { country_name: 'Australia', country_code: 'AU', ambulance_phone: '000' },
        { country_name: 'Austria', country_code: 'AT', ambulance_phone: '144' },
        { country_name: 'Azerbaijan', country_code: 'AZ', ambulance_phone: '103' },
        { country_name: 'Bahamas', country_code: 'BS', ambulance_phone: '911' },
        { country_name: 'Bahrain', country_code: 'BH', ambulance_phone: '999' },
        { country_name: 'Bangladesh', country_code: 'BD', ambulance_phone: '199' },
        { country_name: 'Barbados', country_code: 'BB', ambulance_phone: '511' },
        { country_name: 'Belarus', country_code: 'BY', ambulance_phone: '103' },
        { country_name: 'Belgium', country_code: 'BE', ambulance_phone: '112' },
        { country_name: 'Belize', country_code: 'BZ', ambulance_phone: '911' },
        { country_name: 'Benin', country_code: 'BJ', ambulance_phone: '166' },
        { country_name: 'Bhutan', country_code: 'BT', ambulance_phone: '112' },
        { country_name: 'Bolivia', country_code: 'BO', ambulance_phone: '118' },
        { country_name: 'Bosnia and Herzegovina', country_code: 'BA', ambulance_phone: '124' },
        { country_name: 'Botswana', country_code: 'BW', ambulance_phone: '997' },
        { country_name: 'Brazil', country_code: 'BR', ambulance_phone: '192' },
        { country_name: 'Brunei', country_code: 'BN', ambulance_phone: '991' },
        { country_name: 'Bulgaria', country_code: 'BG', ambulance_phone: '150' },
        { country_name: 'Burkina Faso', country_code: 'BF', ambulance_phone: '17' },
        { country_name: 'Burundi', country_code: 'BI', ambulance_phone: '117' },
        { country_name: 'Cabo Verde', country_code: 'CV', ambulance_phone: '130' },
        { country_name: 'Cambodia', country_code: 'KH', ambulance_phone: '119' },
        { country_name: 'Cameroon', country_code: 'CM', ambulance_phone: '112' },
        { country_name: 'Canada', country_code: 'CA', ambulance_phone: '911' },
        { country_name: 'Central African Republic', country_code: 'CF', ambulance_phone: '117' },
        { country_name: 'Chad', country_code: 'TD', ambulance_phone: '2251' },
        { country_name: 'Chile', country_code: 'CL', ambulance_phone: '131' },
        { country_name: 'China', country_code: 'CN', ambulance_phone: '120' },
        { country_name: 'Colombia', country_code: 'CO', ambulance_phone: '123' },
        { country_name: 'Comoros', country_code: 'KM', ambulance_phone: '77203' },
        { country_name: 'Congo (Congo-Brazzaville)', country_code: 'CG', ambulance_phone: '166' },
        { country_name: 'Costa Rica', country_code: 'CR', ambulance_phone: '911' },
        { country_name: 'Croatia', country_code: 'HR', ambulance_phone: '194' },
        { country_name: 'Cuba', country_code: 'CU', ambulance_phone: '104' },
        { country_name: 'Cyprus', country_code: 'CY', ambulance_phone: '112' },
        { country_name: 'Czechia (Czech Republic)', country_code: 'CZ', ambulance_phone: '155' },
        { country_name: 'Democratic Republic of the Congo', country_code: 'CD', ambulance_phone: '148' },
        { country_name: 'Denmark', country_code: 'DK', ambulance_phone: '112' },
        { country_name: 'Djibouti', country_code: 'DJ', ambulance_phone: '35-35' },
        { country_name: 'Dominica', country_code: 'DM', ambulance_phone: '999' },
        { country_name: 'Dominican Republic', country_code: 'DO', ambulance_phone: '911' },
        { country_name: 'Ecuador', country_code: 'EC', ambulance_phone: '911' },
        { country_name: 'Egypt', country_code: 'EG', ambulance_phone: '123' },
        { country_name: 'El Salvador', country_code: 'SV', ambulance_phone: '911' },
        { country_name: 'Equatorial Guinea', country_code: 'GQ', ambulance_phone: '112' },
        { country_name: 'Eritrea', country_code: 'ER', ambulance_phone: '2911' },
        { country_name: 'Estonia', country_code: 'EE', ambulance_phone: '112' },
        { country_name: 'Eswatini (fmr. "Swaziland")', country_code: 'SZ', ambulance_phone: '977' },
        { country_name: 'Ethiopia', country_code: 'ET', ambulance_phone: '911' },
        { country_name: 'Fiji', country_code: 'FJ', ambulance_phone: '911' },
        { country_name: 'Finland', country_code: 'FI', ambulance_phone: '112' },
        { country_name: 'France', country_code: 'FR', ambulance_phone: '15' },
        { country_name: 'Gabon', country_code: 'GA', ambulance_phone: '1300' },
        { country_name: 'Gambia', country_code: 'GM', ambulance_phone: '116' },
        { country_name: 'Georgia', country_code: 'GE', ambulance_phone: '112' },
        { country_name: 'Germany', country_code: 'DE', ambulance_phone: '112' },
        { country_name: 'Ghana', country_code: 'GH', ambulance_phone: '112' },
        { country_name: 'Greece', country_code: 'GR', ambulance_phone: '166' },
        { country_name: 'Grenada', country_code: 'GD', ambulance_phone: '911' },
        { country_name: 'Guatemala', country_code: 'GT', ambulance_phone: '123' },
        { country_name: 'Guinea', country_code: 'GN', ambulance_phone: '122' },
        { country_name: 'Guinea-Bissau', country_code: 'GW', ambulance_phone: '119' },
        { country_name: 'Guyana', country_code: 'GY', ambulance_phone: '913' },
        { country_name: 'Haiti', country_code: 'HT', ambulance_phone: '118' },
        { country_name: 'Holy See', country_code: 'VA', ambulance_phone: '112' },
        { country_name: 'Honduras', country_code: 'HN', ambulance_phone: '195' },
        { country_name: 'Hungary', country_code: 'HU', ambulance_phone: '104' },
        { country_name: 'Iceland', country_code: 'IS', ambulance_phone: '112' },
        { country_name: 'India', country_code: 'IN', ambulance_phone: '102' },
        { country_name: 'Indonesia', country_code: 'ID', ambulance_phone: '118' },
        { country_name: 'Iran', country_code: 'IR', ambulance_phone: '115' },
        { country_name: 'Iraq', country_code: 'IQ', ambulance_phone: '130' },
        { country_name: 'Ireland', country_code: 'IE', ambulance_phone: '112' },
        { country_name: 'Israel', country_code: 'IL', ambulance_phone: '101' },
        { country_name: 'Italy', country_code: 'IT', ambulance_phone: '118' },
        { country_name: 'Jamaica', country_code: 'JM', ambulance_phone: '110' },
        { country_name: 'Japan', country_code: 'JP', ambulance_phone: '119' },
        { country_name: 'Jordan', country_code: 'JO', ambulance_phone: '191' },
        { country_name: 'Kazakhstan', country_code: 'KZ', ambulance_phone: '103' },
        { country_name: 'Kenya', country_code: 'KE', ambulance_phone: '999' },
        { country_name: 'Kiribati', country_code: 'KI', ambulance_phone: '994' },
        { country_name: 'Kuwait', country_code: 'KW', ambulance_phone: '112' },
        { country_name: 'Kyrgyzstan', country_code: 'KG', ambulance_phone: '103' },
        { country_name: 'Laos', country_code: 'LA', ambulance_phone: '195' },
        { country_name: 'Latvia', country_code: 'LV', ambulance_phone: '113' },
        { country_name: 'Lebanon', country_code: 'LB', ambulance_phone: '140' },
        { country_name: 'Lesotho', country_code: 'LS', ambulance_phone: '121' },
        { country_name: 'Liberia', country_code: 'LR', ambulance_phone: '911' },
        { country_name: 'Libya', country_code: 'LY', ambulance_phone: '193' },
        { country_name: 'Liechtenstein', country_code: 'LI', ambulance_phone: '144' },
        { country_name: 'Lithuania', country_code: 'LT', ambulance_phone: '112' },
        { country_name: 'Luxembourg', country_code: 'LU', ambulance_phone: '112' },
        { country_name: 'Madagascar', country_code: 'MG', ambulance_phone: '124' },
        { country_name: 'Malawi', country_code: 'MW', ambulance_phone: '998' },
        { country_name: 'Malaysia', country_code: 'MY', ambulance_phone: '999' },
        { country_name: 'Maldives', country_code: 'MV', ambulance_phone: '102' },
        { country_name: 'Mali', country_code: 'ML', ambulance_phone: '15' },
        { country_name: 'Malta', country_code: 'MT', ambulance_phone: '112' },
        { country_name: 'Marshall Islands', country_code: 'MH', ambulance_phone: '625-5679' },
        { country_name: 'Mauritania', country_code: 'MR', ambulance_phone: '118' },
        { country_name: 'Mauritius', country_code: 'MU', ambulance_phone: '114' },
        { country_name: 'Mexico', country_code: 'MX', ambulance_phone: '911' },
        { country_name: 'Micronesia', country_code: 'FM', ambulance_phone: '320-2767' },
        { country_name: 'Moldova', country_code: 'MD', ambulance_phone: '903' },
        { country_name: 'Monaco', country_code: 'MC', ambulance_phone: '112' },
        { country_name: 'Mongolia', country_code: 'MN', ambulance_phone: '103' },
        { country_name: 'Montenegro', country_code: 'ME', ambulance_phone: '124' },
        { country_name: 'Morocco', country_code: 'MA', ambulance_phone: '15' },
        { country_name: 'Mozambique', country_code: 'MZ', ambulance_phone: '117' },
        { country_name: 'Myanmar', country_code: 'MM', ambulance_phone: '199' },
        { country_name: 'Namibia', country_code: 'NA', ambulance_phone: '211' },
        { country_name: 'Nauru', country_code: 'NR', ambulance_phone: '110' },
        { country_name: 'Nepal', country_code: 'NP', ambulance_phone: '102' },
        { country_name: 'Netherlands', country_code: 'NL', ambulance_phone: '112' },
        { country_name: 'New Zealand', country_code: 'NZ', ambulance_phone: '111' },
        { country_name: 'Nicaragua', country_code: 'NI', ambulance_phone: '128' },
        { country_name: 'Niger', country_code: 'NE', ambulance_phone: '15' },
        { country_name: 'Nigeria', country_code: 'NG', ambulance_phone: '112' },
        { country_name: 'North Korea', country_code: 'KP', ambulance_phone: '119' },
        { country_name: 'North Macedonia', country_code: 'MK', ambulance_phone: '194' },
        { country_name: 'Norway', country_code: 'NO', ambulance_phone: '113' },
        { country_name: 'Oman', country_code: 'OM', ambulance_phone: '999' },
        { country_name: 'Pakistan', country_code: 'PK', ambulance_phone: '115' },
        { country_name: 'Palau', country_code: 'PW', ambulance_phone: '911' },
        { country_name: 'Palestine State', country_code: 'PS', ambulance_phone: '101' },
        { country_name: 'Panama', country_code: 'PA', ambulance_phone: '911' },
        { country_name: 'Papua New Guinea', country_code: 'PG', ambulance_phone: '111' },
        { country_name: 'Paraguay', country_code: 'PY', ambulance_phone: '911' },
        { country_name: 'Peru', country_code: 'PE', ambulance_phone: '106' },
        { country_name: 'Philippines', country_code: 'PH', ambulance_phone: '911' },
        { country_name: 'Poland', country_code: 'PL', ambulance_phone: '112' },
        { country_name: 'Portugal', country_code: 'PT', ambulance_phone: '112' },
        { country_name: 'Qatar', country_code: 'QA', ambulance_phone: '999' },
        { country_name: 'Romania', country_code: 'RO', ambulance_phone: '112' },
        { country_name: 'Russia', country_code: 'RU', ambulance_phone: '103' },
        { country_name: 'Rwanda', country_code: 'RW', ambulance_phone: '912' },
        { country_name: 'Saint Kitts and Nevis', country_code: 'KN', ambulance_phone: '911' },
        { country_name: 'Saint Lucia', country_code: 'LC', ambulance_phone: '911' },
        { country_name: 'Saint Vincent and the Grenadines', country_code: 'VC', ambulance_phone: '911' },
        { country_name: 'Samoa', country_code: 'WS', ambulance_phone: '996' },
        { country_name: 'San Marino', country_code: 'SM', ambulance_phone: '118' },
        { country_name: 'Sao Tome and Principe', country_code: 'ST', ambulance_phone: '112' },
        { country_name: 'Saudi Arabia', country_code: 'SA', ambulance_phone: '997' },
        { country_name: 'Senegal', country_code: 'SN', ambulance_phone: '17' },
        { country_name: 'Serbia', country_code: 'RS', ambulance_phone: '194' },
        { country_name: 'Seychelles', country_code: 'SC', ambulance_phone: '151' },
        { country_name: 'Sierra Leone', country_code: 'SL', ambulance_phone: '999' },
        { country_name: 'Singapore', country_code: 'SG', ambulance_phone: '995' },
        { country_name: 'Slovakia', country_code: 'SK', ambulance_phone: '155' },
        { country_name: 'Slovenia', country_code: 'SI', ambulance_phone: '112' },
        { country_name: 'Solomon Islands', country_code: 'SB', ambulance_phone: '999' },
        { country_name: 'Somalia', country_code: 'SO', ambulance_phone: '999' },
        { country_name: 'South Africa', country_code: 'ZA', ambulance_phone: '10177' },
        { country_name: 'South Korea', country_code: 'KR', ambulance_phone: '119' },
        { country_name: 'South Sudan', country_code: 'SS', ambulance_phone: '666' },
        { country_name: 'Spain', country_code: 'ES', ambulance_phone: '112' },
        { country_name: 'Sri Lanka', country_code: 'LK', ambulance_phone: '110' },
        { country_name: 'Sudan', country_code: 'SD', ambulance_phone: '999' },
        { country_name: 'Suriname', country_code: 'SR', ambulance_phone: '115' },
        { country_name: 'Sweden', country_code: 'SE', ambulance_phone: '112' },
        { country_name: 'Switzerland', country_code: 'CH', ambulance_phone: '144' },
        { country_name: 'Syria', country_code: 'SY', ambulance_phone: '110' },
        { country_name: 'Tajikistan', country_code: 'TJ', ambulance_phone: '103' },
        { country_name: 'Tanzania', country_code: 'TZ', ambulance_phone: '115' },
        { country_name: 'Thailand', country_code: 'TH', ambulance_phone: '1669' },
        { country_name: 'Timor-Leste', country_code: 'TL', ambulance_phone: '112' },
        { country_name: 'Togo', country_code: 'TG', ambulance_phone: '8200-1800' },
        { country_name: 'Tonga', country_code: 'TO', ambulance_phone: '911' },
        { country_name: 'Trinidad and Tobago', country_code: 'TT', ambulance_phone: '990' },
        { country_name: 'Tunisia', country_code: 'TN', ambulance_phone: '190' },
        { country_name: 'Turkey', country_code: 'TR', ambulance_phone: '112' },
        { country_name: 'Turkmenistan', country_code: 'TM', ambulance_phone: '03' },
        { country_name: 'Tuvalu', country_code: 'TV', ambulance_phone: '911' },
        { country_name: 'Uganda', country_code: 'UG', ambulance_phone: '999' },
        { country_name: 'Ukraine', country_code: 'UA', ambulance_phone: '103' },
        { country_name: 'United Arab Emirates', country_code: 'AE', ambulance_phone: '998' },
        { country_name: 'United Kingdom', country_code: 'GB', ambulance_phone: '999' },
        { country_name: 'United States of America', country_code: 'US', ambulance_phone: '911' },
        { country_name: 'Uruguay', country_code: 'UY', ambulance_phone: '911' },
        { country_name: 'Uzbekistan', country_code: 'UZ', ambulance_phone: '103' },
        { country_name: 'Vanuatu', country_code: 'VU', ambulance_phone: '112' },
        { country_name: 'Venezuela', country_code: 'VE', ambulance_phone: '171' },
        { country_name: 'Vietnam', country_code: 'VN', ambulance_phone: '115' },
        { country_name: 'Yemen', country_code: 'YE', ambulance_phone: '191' },
        { country_name: 'Zambia', country_code: 'ZM', ambulance_phone: '999' },
        { country_name: 'Zimbabwe', country_code: 'ZW', ambulance_phone: '999' },
        { country_name: 'Kosovo', country_code: 'XK', ambulance_phone: '112' },
        { country_name: 'Western Sahara', country_code: 'EH', ambulance_phone: '150' },
        { country_name: 'South Sudan', country_code: 'SS', ambulance_phone: '666' },
        { country_name: 'Taiwan', country_code: 'TW', ambulance_phone: '119' },
        { country_name: 'Somaliland', country_code: '', ambulance_phone: '999' },
        { country_name: 'Palestine', country_code: 'PS', ambulance_phone: '101' },
        { country_name: 'Hong Kong', country_code: 'HK', ambulance_phone: '999' },
        { country_name: 'Macau', country_code: 'MO', ambulance_phone: '999' },                  
    ])
};
